---
title: "spatialDWLS_simulate_data_deconvolution"
output: html_document
---
##Import library of Giotto
```{r}
library(Giotto)
```

##Identification signature genes by using Giotto
```{r}
my_python_path= "python path"
instrs = createGiottoInstructions(python_path = my_python_path)
sc_matrix<-read.table("../../datasets/simulate_data_seqFISH_plus/raw_somatosensory_sc_exp.txt",header=T,row.names = 1)
sc_lable<-read.table("../../datasets/simulate_data_seqFISH_plus/somatosensory_sc_labels.txt",header=F)
sc_cortex <- createGiottoObject(raw_exprs = sc_matrix,instructions = instrs)
sc_cortex <- normalizeGiotto(gobject = sc_cortex)
sc_cortex@cell_metadata$leiden_clus<-as.character(sc_lable$V1)
gini_markers_subclusters = findMarkers_one_vs_all(gobject = sc_cortex,
                                                   method = 'gini',
                                                   expression_values = 'normalized',
                                                   cluster_column = 'leiden_clus')
topgenes_gini = gini_markers_subclusters[, head(.SD, 100), by = 'cluster']
sc_norm_exp <- 2^(sc_cortex@norm_expr)-1

ExprSubset<-sc_norm_exp[as.character(topgenes_gini$genes),]
Sig<-NULL
for (i in as.character(unique(sc_lable$V1))){
  Sig<-cbind(Sig,(apply(ExprSubset,1,function(y) mean(y[which(sc_lable$V1==i)]))))
}
colnames(Sig)<-as.character(unique(sc_lable$V1))
```

##seqFISH+ deconvolution
```{r}
grid_exp<-read.table("../../datasets/simulate_data_seqFISH_plus/simulated_seqFISH_grid_norm_exp.txt",header = 1,row.names = 1)

grid_seqFish <- createGiottoObject(raw_exprs = grid_exp,instructions = instrs)
grid_seqFish <- normalizeGiotto(gobject = grid_seqFish)
grid_seqFish <- calculateHVG(gobject = grid_seqFish)
gene_metadata = fDataDT(grid_seqFish)
featgenes = gene_metadata[hvg == 'yes']$gene_ID
grid_seqFish <- runPCA(gobject = grid_seqFish, genes_to_use = featgenes, scale_unit = F)
signPCA(grid_seqFish, genes_to_use = featgenes, scale_unit = F)
grid_seqFish <- createNearestNetwork(gobject = grid_seqFish, dimensions_to_use = 1:10, k = 10)
grid_seqFish <- doLeidenCluster(gobject = grid_seqFish, resolution = 0.4, n_iterations = 1000)

grid_seqFish<-runDWLSDeconv(gobject = grid_seqFish,sign_matrix = Sig,n_cell = 20)
```